"""Include attributes to Professional tables

Revision ID: 33fd9eb76972
Revises: 90b946c243ba
Create Date: 2024-10-11 17:27:08.388886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '33fd9eb76972'
down_revision: Union[str, None] = '90b946c243ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('professional', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('professional', sa.Column('verified', sa.Boolean(), nullable=False))
    op.add_column('professional', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('professional', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional', 'created_at')
    op.drop_column('professional', 'active')
    op.drop_column('professional', 'verified')
    op.drop_column('professional', 'email')
    op.drop_column('professional', 'avatar_url')
    # ### end Alembic commands ###
