"""Unique value in specialization and insurance table

Revision ID: 90b946c243ba
Revises: 5d42edc92e7e
Create Date: 2024-09-06 22:15:24.397895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90b946c243ba'
down_revision: Union[str, None] = '5d42edc92e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'insurance', ['name'])
    op.create_unique_constraint(None, 'specialization', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specialization', type_='unique')
    op.drop_constraint(None, 'insurance', type_='unique')
    # ### end Alembic commands ###
