# fly.toml app configuration file generated for fast-adv-api on 2023-11-04T20:54:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rede-incluidora-api"
primary_region = "gru"

[build]

[build.args]
INSTALL_PYTHON_VERSION = "3.11"

[deploy]
max_unavailable = 1.0
strategy = "rolling"

[env]

BACKEND_CORS_ORIGINS = "https://rede-incluidora.vercel.app/"
FIRST_SUPERUSER = "arnaldo@turque.com.br"

POSTGRES_SERVER="localhost"
POSTGRES_DB="rede_incluidora"
POSTGRES_USER="postgres"
POSTGRES_PORT = 5432


[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8000
min_machines_running = 0
processes = ["app"]
