"""Correção campo da tabela specialization

Revision ID: 08e445fecf6c
Revises: ee1d56c4f439
Create Date: 2024-09-04 13:23:47.261612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08e445fecf6c'
down_revision: Union[str, None] = 'ee1d56c4f439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialization', sa.Column('professional_id', sa.Integer(), nullable=False))
    op.drop_constraint('specialization_prefessional_id_fkey', 'specialization', type_='foreignkey')
    op.create_foreign_key(None, 'specialization', 'professional', ['professional_id'], ['id'])
    op.drop_column('specialization', 'prefessional_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialization', sa.Column('prefessional_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'specialization', type_='foreignkey')
    op.create_foreign_key('specialization_prefessional_id_fkey', 'specialization', 'professional', ['prefessional_id'], ['id'])
    op.drop_column('specialization', 'professional_id')
    # ### end Alembic commands ###
