"""Create professional model

Revision ID: 230a70c21042
Revises: 9e96c2218454
Create Date: 2024-08-30 14:50:30.118833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '230a70c21042'
down_revision: Union[str, None] = '9e96c2218454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional',
    sa.Column('self_description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('home_service', sa.Boolean(), nullable=False),
    sa.Column('accepts_insurance', sa.Boolean(), nullable=False),
    sa.Column('private_only', sa.Boolean(), nullable=False),
    sa.Column('remote_appointment', sa.Boolean(), nullable=False),
    sa.Column('in_person_appointment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional')
    # ### end Alembic commands ###
