"""Professional insurance table

Revision ID: 31b23fc27260
Revises: c713ef3a3609
Create Date: 2024-09-03 21:46:12.251244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31b23fc27260'
down_revision: Union[str, None] = 'c713ef3a3609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professionalinsurance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_professional', sa.Integer(), nullable=True),
    sa.Column('id_insurance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_insurance'], ['insurance.id'], ),
    sa.ForeignKeyConstraint(['id_professional'], ['professional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professionalinsurance')
    op.drop_table('insurance')
    # ### end Alembic commands ###
