"""Include user_id in professionals table

Revision ID: 85f0cbd9c7c3
Revises: 31b23fc27260
Create Date: 2024-09-03 22:02:44.615945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85f0cbd9c7c3'
down_revision: Union[str, None] = '31b23fc27260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professional', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professional', type_='foreignkey')
    op.drop_column('professional', 'user_id')
    # ### end Alembic commands ###
