"""Padronização de nome das chaves estrangeiras

Revision ID: b69cd180e2f1
Revises: fb85607e89c7
Create Date: 2024-09-04 13:40:57.365947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b69cd180e2f1'
down_revision: Union[str, None] = 'fb85607e89c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionalinsurance', sa.Column('professional_id', sa.Integer(), nullable=True))
    op.add_column('professionalinsurance', sa.Column('insurance_id', sa.Integer(), nullable=True))
    op.drop_constraint('professionalinsurance_id_professional_fkey', 'professionalinsurance', type_='foreignkey')
    op.drop_constraint('professionalinsurance_id_insurance_fkey', 'professionalinsurance', type_='foreignkey')
    op.create_foreign_key(None, 'professionalinsurance', 'insurance', ['insurance_id'], ['id'])
    op.create_foreign_key(None, 'professionalinsurance', 'professional', ['professional_id'], ['id'])
    op.drop_column('professionalinsurance', 'id_insurance')
    op.drop_column('professionalinsurance', 'id_professional')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionalinsurance', sa.Column('id_professional', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('professionalinsurance', sa.Column('id_insurance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'professionalinsurance', type_='foreignkey')
    op.drop_constraint(None, 'professionalinsurance', type_='foreignkey')
    op.create_foreign_key('professionalinsurance_id_insurance_fkey', 'professionalinsurance', 'insurance', ['id_insurance'], ['id'])
    op.create_foreign_key('professionalinsurance_id_professional_fkey', 'professionalinsurance', 'professional', ['id_professional'], ['id'])
    op.drop_column('professionalinsurance', 'insurance_id')
    op.drop_column('professionalinsurance', 'professional_id')
    # ### end Alembic commands ###
