"""professional sppecialization table

Revision ID: c2f9932927f8
Revises: 230a70c21042
Create Date: 2024-09-01 23:09:32.724463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2f9932927f8'
down_revision: Union[str, None] = '230a70c21042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization',
    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('certification', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('year_obtained', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefessional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prefessional_id'], ['professional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialization')
    # ### end Alembic commands ###
