"""Professional tables

Revision ID: ecdf5975d653
Revises: f298d9b675dd
Create Date: 2024-09-05 19:11:49.038556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecdf5975d653'
down_revision: Union[str, None] = 'f298d9b675dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialization',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professionaldata',
    sa.Column('self_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('home_service', sa.Boolean(), nullable=False),
    sa.Column('accepts_insurance', sa.Boolean(), nullable=False),
    sa.Column('private_only', sa.Boolean(), nullable=False),
    sa.Column('remote_appointment', sa.Boolean(), nullable=False),
    sa.Column('in_person_appointment', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('userinsurance',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insurance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insurance_id'], ['insurance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'insurance_id')
    )
    op.create_table('userspecialization',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specialization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'specialization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userspecialization')
    op.drop_table('userinsurance')
    op.drop_table('professionaldata')
    op.drop_table('specialization')
    op.drop_table('insurance')
    # ### end Alembic commands ###
