"""Table adjustes

Revision ID: ee1d56c4f439
Revises: 85f0cbd9c7c3
Create Date: 2024-09-04 13:11:54.842461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee1d56c4f439'
down_revision: Union[str, None] = '85f0cbd9c7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('professional_user_id_fkey', 'professional', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('professional_user_id_fkey', 'professional', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
